name: '📚 Epic request'
description: Suggest a new Epic for this project
labels: ['enhancement', 'needs triage :exclamation:', 'epic']
title: '[Epic]: <enter title here>'
body:
  - type: textarea
    attributes:
      label: What problem are you trying to solve?
      description: A clear and concise description of what the problem is.
      placeholder: 'e.g. I want to …'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you'd like.
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What are the Features associated with this Epic?
      description: |
        A clear and concise description of all acceptance criteria in checkbox-list format.
        The more details you can provide, the better.
      placeholder: |
        #1234
        #2345
        #3456
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context.
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
