-- AI Readiness Assessment scoring rubric v2.0.0
--
-- Implements the 7-dimension assessment instrument (MD v1.0) plus the
-- retained policy_governance dimension from v1 (ADR-006).
-- The config jsonb was generated from
-- packages/shared/src/schemas/audit-scoring.ts createDefaultScoringConfig('2.0.0').
--
-- On apply:
--   1. Deactivates the v1.0.0 rubric row.
--   2. Inserts the v2.0.0 row as the single active rubric.

-- Deactivate v1
update public.scoring_rubrics
set is_active = false
where name = 'audit_readiness'
  and version = '1.0.0';

-- Insert v2
insert into public.scoring_rubrics (name, version, is_active, config, deactivated_at)
values (
  'audit_readiness',
  '2.0.0',
  true,
  '{
    "version": "2.0.0",
    "name": "audit_readiness",
    "description": "Deterministic AI-readiness scoring rubric, v2.0.0 (ADR-006).",
    "display_dimension_mapping": {
      "management_buy_in": "leadership",
      "policy_governance": "leadership",
      "ai_problem_identification": "leadership",
      "data_readiness": "systems",
      "system_integration": "systems",
      "systems_thinking": "process",
      "sop_workflow_automation": "process",
      "current_ai_usage": "readiness",
      "leadership_commitment": "leadership",
      "systems_integration": "systems",
      "technical_infrastructure": "systems",
      "data_quality": "systems",
      "process_automation": "process",
      "staff_readiness": "readiness",
      "change_management": "leadership"
    },
    "question_weights": [
      {"question_id":"data_readiness.q1_1","dimension":"data_readiness","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.data_readiness.q1_1"],"description":"Where core business data lives today.","rationale_template":"Data location maturity score: {value}/4."},
      {"question_id":"data_readiness.q1_2","dimension":"data_readiness","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.data_readiness.q1_2"],"description":"Quality and consistency of data.","rationale_template":"Data quality score: {value}/4."},
      {"question_id":"data_readiness.q1_3","dimension":"data_readiness","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.data_readiness.q1_3"],"description":"Ease of data access for team members.","rationale_template":"Data accessibility score: {value}/4."},
      {"question_id":"data_readiness.q1_4","dimension":"data_readiness","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.data_readiness.q1_4"],"description":"Data documentation maturity.","rationale_template":"Data documentation score: {value}/4."},
      {"question_id":"data_readiness.q1_5","dimension":"data_readiness","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.data_readiness.q1_5"],"description":"Governance of sensitive data.","rationale_template":"Sensitive data governance score: {value}/4."},
      {"question_id":"data_readiness.q1_6","dimension":"data_readiness","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.data_readiness.q1_6"],"description":"Share of data that is machine-readable / structured.","rationale_template":"Machine-readable data share score: {value}/4."},
      {"question_id":"data_readiness.q1_7","dimension":"data_readiness","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.data_readiness.q1_7"],"description":"Frequency of operational data updates.","rationale_template":"Data freshness score: {value}/4."},

      {"question_id":"management_buy_in.q2_1","dimension":"management_buy_in","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.management_buy_in.q2_1"],"description":"Leadership stance on AI adoption.","rationale_template":"Leadership AI stance score: {value}/4."},
      {"question_id":"management_buy_in.q2_2","dimension":"management_buy_in","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.management_buy_in.q2_2"],"description":"Dedicated budget for AI initiatives.","rationale_template":"AI budget allocation score: {value}/4."},
      {"question_id":"management_buy_in.q2_3","dimension":"management_buy_in","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.management_buy_in.q2_3"],"description":"Accountable owner / sponsor for AI efforts.","rationale_template":"AI ownership clarity score: {value}/4."},
      {"question_id":"management_buy_in.q2_4","dimension":"management_buy_in","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.management_buy_in.q2_4"],"description":"Leadership team alignment on AI priorities.","rationale_template":"Leadership alignment score: {value}/4."},
      {"question_id":"management_buy_in.q2_5","dimension":"management_buy_in","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.management_buy_in.q2_5"],"description":"Leadership time-to-value expectation.","rationale_template":"Time-to-value realism score: {value}/4."},
      {"question_id":"management_buy_in.q2_6","dimension":"management_buy_in","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.management_buy_in.q2_6"],"description":"Organizational change responsiveness.","rationale_template":"Change adaptability score: {value}/4."},
      {"question_id":"management_buy_in.q2_7","dimension":"management_buy_in","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.management_buy_in.q2_7"],"description":"AI ROI / success metric definition.","rationale_template":"AI ROI definition score: {value}/4."},

      {"question_id":"ai_problem_identification.q3_1","dimension":"ai_problem_identification","base_weight":0,"scoring_function":"scale_score","question_type":"multi_select","enabled":false,"source_fields":["ai_readiness_assessment.ai_problem_identification.q3_1_selections"],"description":"Target efficiency problems (roadmap — unscored)."},
      {"question_id":"ai_problem_identification.q3_2","dimension":"ai_problem_identification","base_weight":0,"scoring_function":"scale_score","question_type":"free_text","enabled":false,"source_fields":["ai_readiness_assessment.ai_problem_identification.q3_2_text"],"description":"Most painful process (roadmap — unscored)."},
      {"question_id":"ai_problem_identification.q3_3","dimension":"ai_problem_identification","base_weight":0.2,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.ai_problem_identification.q3_3"],"description":"Clarity of the specific problem to solve with AI.","rationale_template":"Problem articulation clarity score: {value}/4."},
      {"question_id":"ai_problem_identification.q3_4","dimension":"ai_problem_identification","base_weight":0.2,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.ai_problem_identification.q3_4"],"description":"Knowledge of problem cost.","rationale_template":"Problem cost quantification score: {value}/4."},
      {"question_id":"ai_problem_identification.q3_5","dimension":"ai_problem_identification","base_weight":0.2,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.ai_problem_identification.q3_5"],"description":"Prioritization of which problem to tackle first.","rationale_template":"Problem prioritization score: {value}/4."},
      {"question_id":"ai_problem_identification.q3_6","dimension":"ai_problem_identification","base_weight":0.2,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.ai_problem_identification.q3_6"],"description":"Repeatability of the target process.","rationale_template":"Process repeatability score: {value}/4."},
      {"question_id":"ai_problem_identification.q3_7","dimension":"ai_problem_identification","base_weight":0.2,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.ai_problem_identification.q3_7"],"description":"Current measurable performance of the target process.","rationale_template":"Process performance baseline score: {value}/4."},

      {"question_id":"systems_thinking.q4_1","dimension":"systems_thinking","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.systems_thinking.q4_1"],"description":"Problem response maturity.","rationale_template":"Problem response maturity score: {value}/4."},
      {"question_id":"systems_thinking.q4_2","dimension":"systems_thinking","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.systems_thinking.q4_2"],"description":"Cross-departmental workflow visibility.","rationale_template":"Cross-functional visibility score: {value}/4."},
      {"question_id":"systems_thinking.q4_3","dimension":"systems_thinking","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.systems_thinking.q4_3"],"description":"Downstream impact consideration.","rationale_template":"Downstream impact awareness score: {value}/4."},
      {"question_id":"systems_thinking.q4_4","dimension":"systems_thinking","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.systems_thinking.q4_4"],"description":"Improve / automate / eliminate decision framework.","rationale_template":"Process evaluation framework score: {value}/4."},
      {"question_id":"systems_thinking.q4_5","dimension":"systems_thinking","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.systems_thinking.q4_5"],"description":"Tool and process decision documentation.","rationale_template":"Decision documentation score: {value}/4."},
      {"question_id":"systems_thinking.q4_6","dimension":"systems_thinking","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.systems_thinking.q4_6"],"description":"Change measurement approach.","rationale_template":"Change measurement maturity score: {value}/4."},
      {"question_id":"systems_thinking.q4_7","dimension":"systems_thinking","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.systems_thinking.q4_7"],"description":"Workflow decomposition comfort.","rationale_template":"Workflow decomposition comfort score: {value}/4."},

      {"question_id":"system_integration.q5_1","dimension":"system_integration","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.system_integration.q5_1"],"description":"Tool inventory status.","rationale_template":"Tech stack inventory maturity score: {value}/4."},
      {"question_id":"system_integration.q5_2","dimension":"system_integration","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.system_integration.q5_2"],"description":"Inter-system data sharing.","rationale_template":"System data-sharing score: {value}/4."},
      {"question_id":"system_integration.q5_3","dimension":"system_integration","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.system_integration.q5_3"],"description":"API / integration capabilities.","rationale_template":"API capability score: {value}/4."},
      {"question_id":"system_integration.q5_4","dimension":"system_integration","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.system_integration.q5_4"],"description":"Identity and access management maturity.","rationale_template":"Identity management maturity score: {value}/4."},
      {"question_id":"system_integration.q5_5","dimension":"system_integration","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.system_integration.q5_5"],"description":"Manual data movement effort.","rationale_template":"Data movement automation score: {value}/4."},
      {"question_id":"system_integration.q5_6","dimension":"system_integration","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.system_integration.q5_6"],"description":"Technical integration capacity.","rationale_template":"Integration technical capacity score: {value}/4."},
      {"question_id":"system_integration.q5_7","dimension":"system_integration","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.system_integration.q5_7"],"description":"Tech stack stability and currency.","rationale_template":"Tech stack health score: {value}/4."},

      {"question_id":"sop_workflow_automation.q6_1","dimension":"sop_workflow_automation","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.sop_workflow_automation.q6_1"],"description":"SOP documentation coverage.","rationale_template":"SOP coverage score: {value}/4."},
      {"question_id":"sop_workflow_automation.q6_2","dimension":"sop_workflow_automation","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.sop_workflow_automation.q6_2"],"description":"SOP adherence consistency.","rationale_template":"SOP adherence score: {value}/4."},
      {"question_id":"sop_workflow_automation.q6_3","dimension":"sop_workflow_automation","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.sop_workflow_automation.q6_3"],"description":"SOP maintenance cadence.","rationale_template":"SOP maintenance score: {value}/4."},
      {"question_id":"sop_workflow_automation.q6_4","dimension":"sop_workflow_automation","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.sop_workflow_automation.q6_4"],"description":"Existing automation breadth.","rationale_template":"Automation breadth score: {value}/4."},
      {"question_id":"sop_workflow_automation.q6_5","dimension":"sop_workflow_automation","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.sop_workflow_automation.q6_5"],"description":"Automation maintenance durability.","rationale_template":"Automation reliability score: {value}/4."},
      {"question_id":"sop_workflow_automation.q6_6","dimension":"sop_workflow_automation","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.sop_workflow_automation.q6_6"],"description":"Role-based process standardization.","rationale_template":"Role-based standardization score: {value}/4."},
      {"question_id":"sop_workflow_automation.q6_7","dimension":"sop_workflow_automation","base_weight":0.143,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.sop_workflow_automation.q6_7"],"description":"Exception-handling documentation.","rationale_template":"Exception handling maturity score: {value}/4."},

      {"question_id":"current_ai_usage.q7_1","dimension":"current_ai_usage","base_weight":0.167,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.current_ai_usage.q7_1"],"description":"Current organizational AI tool usage.","rationale_template":"AI tool adoption depth score: {value}/4."},
      {"question_id":"current_ai_usage.q7_2","dimension":"current_ai_usage","base_weight":0,"scoring_function":"scale_score","question_type":"multi_select","enabled":false,"source_fields":["ai_readiness_assessment.current_ai_usage.q7_2_selections"],"description":"Current AI tools in use (roadmap — unscored)."},
      {"question_id":"current_ai_usage.q7_3","dimension":"current_ai_usage","base_weight":0.167,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.current_ai_usage.q7_3"],"description":"AI use policy maturity.","rationale_template":"AI policy maturity score: {value}/4."},
      {"question_id":"current_ai_usage.q7_4","dimension":"current_ai_usage","base_weight":0.167,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.current_ai_usage.q7_4"],"description":"Team AI literacy.","rationale_template":"AI literacy score: {value}/4."},
      {"question_id":"current_ai_usage.q7_5","dimension":"current_ai_usage","base_weight":0.167,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.current_ai_usage.q7_5"],"description":"AI output evaluation process.","rationale_template":"AI output review maturity score: {value}/4."},
      {"question_id":"current_ai_usage.q7_6","dimension":"current_ai_usage","base_weight":0.167,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.current_ai_usage.q7_6"],"description":"AI experimentation support.","rationale_template":"AI experimentation support score: {value}/4."},
      {"question_id":"current_ai_usage.q7_7","dimension":"current_ai_usage","base_weight":0.167,"scoring_function":"scale_score","question_type":"scale_0_to_4","enabled":true,"scale_score_config":{"min_scale":0,"max_scale":4,"linear_mapping":true},"source_fields":["ai_readiness_assessment.current_ai_usage.q7_7"],"description":"AI tool connectivity to data/systems.","rationale_template":"AI system connectivity score: {value}/4."},

      {"question_id":"policy.has_ai_policy","dimension":"policy_governance","base_weight":0.5,"scoring_function":"bool_score","question_type":"boolean","enabled":true,"source_fields":["ai_readiness.policy.has_ai_policy"],"rationale_template":"A documented AI use policy exists: {value}.","description":"A formal or informal AI policy is in place."},
      {"question_id":"policy.has_data_classification","dimension":"policy_governance","base_weight":0.3,"scoring_function":"bool_score","question_type":"boolean","enabled":true,"source_fields":["ai_readiness.policy.has_data_classification"],"rationale_template":"Data classification scheme exists: {value}.","description":"A data classification scheme is in place."},
      {"question_id":"policy.sensitive_data_appetite","dimension":"policy_governance","base_weight":0.2,"scoring_function":"enum_score","question_type":"single_select","enabled":true,"enum_score_config":{"value_score_mapping":{"none":90,"limited":70,"open":30}},"source_fields":["ai_readiness.policy.sensitive_data_appetite"],"rationale_template":"Sensitive-data appetite stance: {value}.","description":"Stance on sending sensitive data to AI tools."}
    ],
    "dimension_weights": [
      {"dimension":"data_readiness","overall_weight":0.20,"min_score_threshold":50,"description":"Data location, quality, accessibility, documentation, governance, structure, and freshness."},
      {"dimension":"management_buy_in","overall_weight":0.15,"min_score_threshold":60,"description":"Leadership stance, budget, ownership, alignment, expectations, change readiness, and ROI definition."},
      {"dimension":"policy_governance","overall_weight":0.10,"min_score_threshold":55,"description":"AI governance, data classification, and sensitive-data appetite."},
      {"dimension":"ai_problem_identification","overall_weight":0.05,"min_score_threshold":40,"description":"Problem clarity, cost quantification, prioritization, repeatability, and baseline metrics."},
      {"dimension":"systems_thinking","overall_weight":0.12,"min_score_threshold":50,"description":"Root-cause analysis, cross-functional visibility, impact awareness, and measurement discipline."},
      {"dimension":"system_integration","overall_weight":0.15,"min_score_threshold":50,"description":"Tool inventory, data sharing, API coverage, identity management, and integration capacity."},
      {"dimension":"sop_workflow_automation","overall_weight":0.13,"min_score_threshold":50,"description":"SOP coverage, adherence, maintenance, automation breadth, and exception handling."},
      {"dimension":"current_ai_usage","overall_weight":0.10,"min_score_threshold":40,"description":"AI adoption depth, policy, literacy, output review, experimentation, and connectivity."}
    ],
    "readiness_tiers": [
      {"label":"Foundational","min":0,"max":39,"description":"Prerequisites missing; focus on data, sponsorship, and documentation before deployment."},
      {"label":"Emerging","min":40,"max":59,"description":"Pockets of readiness; viable for a tightly scoped pilot."},
      {"label":"Operational","min":60,"max":79,"description":"Ready for production workflows in 1–2 functions."},
      {"label":"Scaling","min":80,"max":100,"description":"Ready for multi-workflow / agentic deployment and orchestration."}
    ],
    "total_score_calculation": "weighted_average",
    "passing_threshold": 60,
    "created_by": "system",
    "is_active": true,
    "changelog": []
  }'::jsonb,
  null
);
